IMAGE_SIZE = 28
DATASET = "mnist"
SOURCE_DOMAIN = "mnist"
TARGET_DOMAIN = "usps"


BATCH_SIZE = 50

NUM_WORKERS = 4
N_EPOCHS_PRETRAINING = 10
N_EPOCHS_ADAPT = 10
STEPS_PER_EPOCH_PRETRAINING = 500
STEPS_PER_EPOCH = 145
VAL_FREQ = 1
SAVE_MODEL_FREQ = 10
IS_PRETRAINING_STAGE = True


CHECKPOINT = 'checkpoints/ADDA_PRETRAINED/epoch_30.pt'