IMAGE_SIZE = 28
DATASET = "mnist"
SOURCE_DOMAIN = "mnist"
TARGET_DOMAIN = "usps"


BATCH_SIZE = 128

NUM_WORKERS = 4
N_EPOCHS_PRETRAINING = 201
N_EPOCHS_ADAPT = 401
STEPS_PER_EPOCH = 1
VAL_FREQ = 1
SAVE_MODEL_FREQ = 50
IS_PRETRAINING_STAGE = True


CHECKPOINT = 'checkpoints/ADDA_PRETRAINED/epoch_200.pt'